- name: Cloning .dotfiles
  ansible.builtin.git:
    repo: 'git@github.com:mikebarkmin/.dotfiles.git'
    dest: "{{ dotfiles_home }}"
    recursive: yes
    update: no
    accept_hostkey: yes
    version: main

- name: Stow dotfiles
  shell: "cd $HOME/.dotfiles && ./install-{{ dotfiles_context }}"
