- name: Makes sure fonts directory exists
  file:
    path: "{{dotfiles_user_home}}/.local/share/fonts"
    recurse: yes
    state: directory

- name: Install fonts
  unarchive:
    src: "{{ item }}"
    dest: "{{ dotfiles_user_home }}/.local/share/fonts"
    remote_src: yes
  with_items: "{{ fonts }}"

- name: 'rebuild fonts cache'
  become: yes
  shell: 'fc-cache -v -f'
